### PR TITLE
Dev fix db lock

### PR DESCRIPTION
**Pull request by spangin**

### CODE REVIEW

**Comment by dnck** [comment]
I noticed the other day that I could not read the  spent-addresses-db because it had a LOCK on it. Does this PR fix that?

**Comment by spangin** [comment]
> I noticed the other day that I could not read the spent-addresses-db because it had a LOCK on it. Does this PR fix that?
Yes. In this fix RocksDBPersistenceProvider instance is created and closed correctly. So the DB can be used again.

**Comment by dnck** [comment]
> > I noticed the other day that I could not read the spent-addresses-db because it had a LOCK on it. Does this PR fix that?
> 
> Yes. In this fix RocksDBPersistenceProvider instance is created and closed correctly. So the DB can be used again.

Hmmmm.... when I cherry-picked the commits, I actually had problems (the output is above). I did cherry-pick the commits out of order. Might that have been my problem? 

Also, if you have some chance, I made some changes to the SpentAddressesProviderImpl in my PR 247. Is there any possibility of merging these into your branch?

**Comment by spangin** [comment]
>lso, if you have some chance, I made some changes to the SpentAddressesProviderImpl in my PR 247. Is there any possibility of merging these into your branch?

My fix is not big, so I'll be able to resolve the conflicts if your PR be approved firstly.
The 2nd way is I can add the code to your branch. It will not take much time.

**Pull request merged**
